### ISSUE TITLE
是否能上传完整的功能包

### ISSUE THREAD

**Issue by 5204338** [laitathei/YOLOv5-Pytorch-TensorRT#1]
大佬能放个完整一些的项目嘛，比如，将YOLO识别目标物的像素坐标转换到相机坐标系下吗，以及完整的功能包

**Comment by laitathei** [comment]
I already implement the coordinates transformation into the program, you can check it [inference_ros_trt_v2.py](https://github.com/laitathei/YOLOv5-Pytorch-TensorRT/blob/main/inference_ros_trt_v2.py)
